### ISSUE TITLE
Add current date to output file name

### ISSUE THREAD

**Issue by emkaser** [uga-libraries/hub-monitoring#93]
For accession_completeness_report.py and risk_update.py, add the current date to the file name of the output CSVs

**Comment by amhanson9** [comment]
Updated all script outputs without a date. Examples:
accession_completness_report_2024-08-30.csv [accession_completeness_report.py]
combined_format_data_2024-08-30.csv [format_list.py]
update_risk_log__2024-08-30.csv [risk_update.py]
