### ISSUE TITLE
Add column for initial manifest CSV

### ISSUE THREAD

**Issue by emkaser** [uga-libraries/hub-monitoring#98]
Add a column that indicates whether or not an accession includes an initial manifest CSV.

File name string pattern: 'initialmanifest_[YYYYMMDD].csv'

**Comment by amhanson9** [comment]
Columns in the report are now: 'Status', 'Collection', 'Accession', 'Preservation_Log', 'Full_Risk', 'Initial_Manifest', 'Bag'. The test for initial manifest is starts with "initialmanifest" and ends with ".csv". @emkaser, this is consistent with how we identify a full risk csv, but if you find it isn't accurate enough, we can switch to regex that matches the date as well.
